# 数据库配置
database:
  host: localhost
  port: 3306
  user: bio_user
  password: bio_pass
  db_name: bio_db

# 输入 json 配置
ingestion:
  lims_data_path: /path/to/LimsData/
  scan_interval: 1800  # 30 minutes

# 测序数据配置
sequence_data:
  sequence_data_path: /path/to/sequence
  sequence_name: Sequenator
  dir1: no_sample_id
  dir2: fastq_pass
  key_file: html

# 原始数据字段映射
fields_mapping:
  project:
    key: Client
    fields:
      project_id: Client
      custom_name: Custom_name
      user_name: user_name
      mobile: Mobile
      remarks: Remarks
  sample:
    key: Detect_no
    fields:
      sample_id: Detect_no
      project_id: Client
      sample_name: Sample_name
      sample_type: Sample_type
      sample_type_raw: Sample_type_raw
      resistance_type: Resistance_type
      project_type: Project
      species_name: Species_name
      genome_size: Genome_size
      data_volume: Data_volume
      ref: Ref
      plasmid_length: PLASMID_LENGTH
      length: Length
  batch:
    key: Batch_id
    fields:
      batch_id: Batch_id
      sequencer_id: Sequencer_id
      laboratory: Laboratory
  sequence:
    key: [Detect_no, Batch_id]
    fields:
      sample_id: Detect_no
      batch_id: Batch_id
      board: Board
      board_id: Board_id
      machine_ver: Machine_ver
      barcode_type: Barcode_type
      barcode_prefix: Barcode_prefix
      barcode_number: Barcode_number
      reanalysis_times: Reanalysis_times
      experiment_times: Experiment_times
      allanalysis_times: Allanalysis_times
      experiment_no: Experiment_no
      sample_con: Sample_con
      sample_status: Sample_status
      unqualifytime: Unqualifytime
      report_path: Report_path
      report_raw_path: Report_raw_path

# 路径模板
sequence_run:
  lab_sequencer_id_template: "{laboratory}{sequence_name}{sequencer_id}"
  barcode_template: "{barcode_prefix}{barcode_number}"
  batch_id_path_template: "{sequence_data_path}/{lab_sequencer_id}/{batch_id}"
  raw_data_path_template: "{batch_id_path}/{dir1}/{run_name}/{dir2}/{barcode}"



# 项目类型分析路径
project_type:
  16SAMP: "/path/to/16s"
  Bacterial_assembly: "/path/to/bacass"

# 新字段规则
new_field_rules:
  - field_name: new_field
    table: sequence
    data_type: VARCHAR(50)
    default_value: ""
    action: reanalyze

# 更新触发规则
table_update_triggers:
  project:
    update_only:
      - custom_name
      - user_name
      - mobile
      - remarks
    reanalyze: []
    newrecord:
      - project_id
  sample:
    update_only:
      - sample_name
      - sample_type
      - sample_type_raw
      - resistance_type
      - species_name
      - genome_size
      - data_volume
      - ref
      - plasmid_length
      - length
    reanalyze:
      - project_type
    newrecord:
      - sample_id
  batch:
    update_only: []
    reanalyze:
      - sequencer_id
      - laboratory
    newrecord:
      - batch_id
  sequence:
    update_only:
      - board
      - board_id
      - machine_ver
      - barcode_type
      - reanalysis_times
      - experiment_times
      - allanalysis_times
      - experiment_no
      - sample_con
      - sample_status
      - unqualifytime
      - report_path
      - report_raw_path
    reanalyze:
      - barcode_prefix
      - barcode_number
    newrecord:
      - sample_id
      - batch_id